[versions]
lombok = "1.18.42"
adventure-libraries = "4.24.0"
adventure-platform = "4.4.1"
expiringmap = "0.5.11"
exp4j = "0.4.8"
itemnbtapi = "2.15.5"
annotations = "24.1.0"
junit-jupiter = "5.9.0"
xseries = "13.6.0"
mythicmobs = "5.6.1"
mongo = "5.0.1"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
adventure-libraries = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-libraries" }
adventure-platform = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
expiringmap = { module = "net.jodah:expiringmap", version.ref  = "expiringmap"}
itemnbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "itemnbtapi" }
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
xseries = { module = "com.github.cryptomorin:XSeries", version.ref = "xseries" }
mongo-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongo" }
mythicmobs = { module = "io.lumine:Mythic-Dist", version.ref = "mythicmobs" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
